---
- name: Ensure Gluster brick and mount directories exist.
  file:
    path: "{{ glusterfs_brick_dir }}"
    state: directory
    owner: root
    group: www-data
    recurse: yes
    mode: 0775
  with_items:
    - "{{ glusterfs_brick_dir }}"
    - "{{ glusterfs_mount_dir }}"

# Gluster volume configuration.
- name: Check if Gluster volumes already exist.
  shell: "gluster volume info"
  changed_when: false
  register: gluster_volume_info

- name: Connect to Gluster peers.
  shell: "gluster peer probe {{ item }}"
  register: gluster_peer_probe
  changed_when: "'already in peer list' not in gluster_peer_probe.stdout"
  with_items: groups.webservers
  when: "'Volume Name: gluster' not in gluster_volume_info.stdout"

- name: Create Gluster volume.
  shell: "gluster volume create {{ glusterfs_brick_name }} {{ glusterfs_brick_config }}"
  register: gluster_volume_create
  changed_when: "'successful' in gluster_volume_create.stdout"
  when: "inventory_hostname == groups.webservers[0] and 'Volume Name: gluster' not in gluster_volume_info.stdout"

- name: Ensure Gluster volume is started.
  shell: "gluster volume start {{ glusterfs_brick_name }}"
  register: gluster_volume_start
  changed_when: "'successful' in gluster_volume_start.stdout"
  when: "inventory_hostname == groups.webservers[0] and 'Volume Name: gluster' not in gluster_volume_info.stdout"

# Mount configuration.
- name: Update fstab to include Gluster mount.
  lineinfile:
    dest: /etc/fstab
    regexp: '{{ glusterfs_mount_dir }}'
    line: '{{ groups.webservers[0] }}:/{{ glusterfs_brick_name }} {{ glusterfs_mount_dir }} glusterfs defaults,_netdev 0 0'

- name: Check if Gluster volume is mounted.
  shell: "grep -qs '{{ glusterfs_mount_dir }}' /proc/mounts"
  changed_when: false
  failed_when: false
  register: gluster_mount

- name: Mount the Gluster volume.
  command: "mount {{ glusterfs_mount_dir }}"
  when: gluster_mount.rc != 0
