---
firewall_allowed_tcp_ports:
  - 22
  - 80
  # For Gluster.
  - 111
  # Port-mapper for Gluster 3.4+.
  # - 2049
  # Gluster Daemon.
  - 24007
  # 24009+ for Gluster <= 3.3; 49152+ for Gluster 3.4+ (one port per server).
  - 24009
  - 24010
  - 24011
  # Gluster inline NFS server.
  - 38465
  - 38466
  - 38467
firewall_allowed_udp_ports:
  - 111

firewall_additional_rules:
  - "iptables -A INPUT -p tcp --dport 4949 -s {{ groups.balancer[0] }} -j ACCEPT"

# Nginx configuration.
nginx_default_release: wheezy-backports # For Nginx 1.6.x instead of 1.2.x.
nginx_worker_processes: "4" # Set to number of CPU cores on Pi.
nginx_worker_connections: "512"
nginx_client_max_body_size: "64m"
nginx_keepalive_timeout: "65"
nginx_remove_default_vhost: true
nginx_vhosts: []

# PHP configuration.
php_webserver_daemon: "nginx"
php_packages:
  - php5
  - php5-fpm
  - php5-cli
  - php5-common
  - php5-curl
  - php5-dev
  - php5-gd
  - php5-mcrypt
  - php-pear
  - php-apc
php_enable_php_fpm: true
php_memory_limit: "128M"
php_max_execution_time: "240"
php_apc_enabled_in_ini: true
php_apc_stat: "0"

# Don't keep updating Drush once installed.
drush_keep_updated: false

# Gluster configuration.
gluster_brick_dir: /srv/gluster/brick
# gluster_mount_dir: "" # Defined in global vars file.
gluster_brick_name: gluster
# Note: This is hardcoded for 3 webservers. Adjust accordingly.
gluster_brick_config:
  "replica 3 transport tcp
  {{ groups.webservers[0] }}:{{ gluster_brick_dir }}
  {{ groups.webservers[1] }}:{{ gluster_brick_dir }}
  {{ groups.webservers[2] }}:{{ gluster_brick_dir }}"

# Munin settings.
munin_node_allowed_ips:
  - "^{{ groups.balancer[0] | replace('.', '\\.') }}$"
