---
firewall_allowed_tcp_ports:
  - 22
  - 80
  # For GlusterFS.
  - 111
  - 24007
  - 24008
  - 24009
  - 24010
  - 24011
  - 49152
  - 49153
  - 49154
firewall_allowed_udp_ports:
  - 111

# Nginx configuration.
nginx_default_release: wheezy-backports # For Nginx 1.6.x instead of 1.2.x.
nginx_worker_processes: "4" # Set to number of CPU cores on Pi.
nginx_worker_connections: "512"
nginx_client_max_body_size: "64m"
nginx_keepalive_timeout: "65"
nginx_remove_default_vhost: true
nginx_vhosts: []

# PHP configuration.
php_webserver_daemon: "nginx"
php_packages:
  - php5
  - php5-fpm
  - php5-cli
  - php5-common
  - php5-curl
  - php5-dev
  - php5-gd
  - php5-mcrypt
  - php5-redis
  - php-pear
  - php-apc
php_enable_php_fpm: true
php_memory_limit: "128M"
php_apc_enabled_in_ini: true
php_apc_stat: "0"

# GlusterFS configuration.
glusterfs_brick_dir: /srv/gluster/brick
# glusterfs_mount_dir: "" # Defined in global vars file.
glusterfs_brick_name: gluster
# Note: This is hardcoded for 3 webservers. Adjust accordingly.
glusterfs_brick_config:
  "replica 3 transport tcp
  {{ groups.webservers[0] }}:{{ glusterfs_brick_dir }}
  {{ groups.webservers[1] }}:{{ glusterfs_brick_dir }}
  {{ groups.webservers[2] }}:{{ glusterfs_brick_dir }}"
