---
- hosts: webservers
  sudo: yes

  vars_files:
    - ../vars.yml
    - vars.yml

  roles:
    - geerlingguy.firewall
    - geerlingguy.nginx

  tasks:
    - name: Copy default server-specific html file in place.
      template:
        src: index.html.j2
        dest: /usr/share/nginx/www/index.html
        mode: 0644
