---
- hosts: webservers
  sudo: yes

  vars_files:
    - ../vars.yml
    - vars.yml

  roles:
    - geerlingguy.firewall
    - geerlingguy.nginx
    - geerlingguy.php
    - geerlingguy.php-mysql
    - geerlingguy.drush
    - geerlingguy.git

  tasks:
    - name: Copy vhost configuration into place.
      template:
        src: drupal.conf.j2
        dest: /etc/nginx/sites-enabled/drupal.conf
        mode: 0644
      notify: restart nginx

    - include: nfs-share.yml
