---
- hosts: webservers
  become: yes

  vars_files:
    - ../vars.yml
    - vars.yml

  roles:
    - { role: geerlingguy.firewall, tags: ['firewall'] }
    - { role: geerlingguy.security, tags: ['security'] }
    - { role: geerlingguy.nginx, tags: ['nginx'] }
    - { role: geerlingguy.php, tags: ['php'] }
    - { role: geerlingguy.php-mysql, tags: ['php'] }
    - { role: geerlingguy.drush, tags: ['drush'] }
    - { role: geerlingguy.git, tags: ['git'] }
    - { role: geerlingguy.munin-node, tags: ['munin-node'] }
    - { role: geerlingguy.nfs, tags: ['nfs'] }
    - { role: ../roles/leds, tags: ['leds'] }

  tasks:
    - include: tasks/extras.yml
    - include: tasks/config.yml
    - include: tasks/nfs.yml
    - include: tasks/led-monitor.yml
