---
- hosts: 127.0.0.1
  connection: local
  sudo: yes

  vars_files:
    - vars.yml

  pre_tasks:
    - include: ../../../playbooks/wheezy-backports.yml

  roles:
    - geerlingguy.firewall
    - geerlingguy.nginx
    - geerlingguy.mysql
    - geerlingguy.php
    - geerlingguy.php-mysql
    - geerlingguy.composer
    - geerlingguy.drush
    - geerlingguy.git
