---
services: docker

addons:
  hosts:
    - cluster.pidramble.test
    - kube1

install:
  - docker pull geerlingguy/docker-debian9-ansible:latest
  - cp example.config.yml config.yml

script:
  # - "travis_wait 30 ./testing/docker/docker-playbook-test.sh"
  - ./testing/docker/docker-playbook-test.sh
