---
services: docker

addons:
  hosts:
    - cluster.pidramble.test
    - registry.pidramble.test
    - kube1

before_install:
  # Install the latest Docker version on Travis CI.
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

install:
  - docker pull geerlingguy/docker-debian10-ansible:latest
  - cp example.config.yml config.yml

script:
  # - "travis_wait 30 ./testing/docker/docker-playbook-test.sh"
  - ./testing/docker/docker-playbook-test.sh

after_failure:
  - docker exec --tty dramble env TERM=xterm journalctl --no-pager -u kubelet
