---
services: docker

env:
  matrix:
    # Test each playbook individually.
    - playbook: balancer
    - playbook: database
    - playbook: web
    # - playbook: drupal

install:
  - docker pull geerlingguy/docker-debian8-ansible:latest

script:
  - ./testing/docker/docker-playbook-test.sh
