---
# MySQL configuration.
mysql_drupal_password: aaiQyjrcdvkxX6fg7UeM
mysql_root_password: mm2vnyboVrndryde4kJR

# Drupal filesystem configuration.
nfs_mount_dir: /mnt/nfs

# Security configuration.
security_sudoers_passwordless:
  - pi

# DigitalOcean configuration (use to test the infrastructure on DigitalOcean).
digitalocean_api_token: "YOUR_TOKEN_HERE"
digitalocean_droplet_state: present
