---
# Drupal configuration.
drupal8_domain: cluster.pidramble.test
drupal8_docker_image: geerlingguy/drupal:latest-arm32v7

# MySQL configuration.
mysql_drupal_password: aaiQyjrcdvkxX6fg7UeM
mysql_root_password: mm2vnyboVrndryde4kJR

# Drupal filesystem configuration.
nfs_mount_dir: /mnt/nfs

# Security configuration.
security_sudoers_passwordless:
  - pi

# Docker configuration.
docker_registry_image: vsellier/docker-registry-arm:2.7.0
docker_registry_domain: registry.pidramble.test
docker_registry_http_secret: fdb19409c851605cd6c46615888d4c0e37858121df7c
