---
- hosts: dramble
  become: yes

  vars_files:
    - vars/main.yml
    - config.yml

  pre_tasks:
    - import_tasks: tasks/test-setup.yml
      when: deploy_target != 'pi'
      tags: ['always']

    - name: Ensure dependencies are installed.
      apt:
        name:
          - sudo
          - openssh-server
        state: present

    - import_tasks: tasks/cgroup-features.yml
    - import_tasks: tasks/disable-swap.yml
      tags: ['always']

    - name: Set the master node IP.
      set_fact:
        kubernetes_master_ip: "{{ hostvars['kube1']['ansible_host'] }}"
      tags: ['always']

  roles:
    # TODO: Re-enable firewall once I can figure out exactly which ports are
    # required to get cni, flannel, etc. all working correctly.
    # - { role: geerlingguy.firewall, tags: ['firewall'] }

    - role: geerlingguy.security
      tags: ['security']

    - role: geerlingguy.swap
      tags: ['always', 'swap']
      when: deploy_target == 'vagrant'

    - role: geerlingguy.nfs
      tags: ['nfs']
      when: deploy_target != 'docker'

    - role: geerlingguy.pip
      tags: ['pip', 'docker']

    - role: docker-arm
      tags: ['docker']

    - role: geerlingguy.kubernetes
      tags: ['kubernetes']

    - role: leds
      tags: ['leds']

  tasks:
    - include_tasks: tasks/nfs.yml
      tags: ['nfs']
      when: deploy_target != 'docker'

    - import_tasks: tasks/led-monitor.yml
      tags: ['leds']

    - import_tasks: tasks/k8s-services.yml
      tags: ['kubernetes']

    - import_tasks: tasks/k8s-nfs.yml
      tags: ['kubernetes', 'nfs']

    - import_tasks: tasks/k8s-docker-registry.yml
      tags: ['kubernetes', 'docker', 'registry']

    - import_tasks: tasks/k8s-drupal8.yml
      tags: ['drupal']
