---
- hosts: dramble
  become: yes

  vars_files:
    - vars/main.yml
    - config.yml

  pre_tasks:
    - name: Ensure dependencies are installed.
      apt: name={{ item }} state=present
      with_items:
        - sudo
        - openssh-server

    - import_tasks: tasks/cgroup-features.yml

    - name: Disable swap.
      command: >
        dphys-swapfile swapoff &&
        dphys-swapfile uninstall &&
        systemctl disable dphys-swapfile
      when: ansible_swaptotal_mb > 0
      tags: ['always']

    # See: https://github.com/geerlingguy/raspberry-pi-dramble/issues/65
    # - name: Ensure rpcbind is purged (first run only).
    #   apt: name=rpcbind state=absent purge=yes

  roles:
    # TODO: Re-enable firewall once I can figure out exactly which ports are
    # required to get cni, flannel, etc. all working correctly.
    # - { role: geerlingguy.firewall, tags: ['firewall'] }
    - { role: geerlingguy.security, tags: ['security'] }
    - { role: geerlingguy.nfs, tags: ['nfs'] }
    - { role: geerlingguy.pip, tags: ['pip', 'docker'] }
    - { role: docker-arm, tags: ['docker'] }
    - { role: geerlingguy.kubernetes, tags: ['kubernetes'] }
    - { role: leds, tags: ['leds'] }

  tasks:
    # TODO: See https://github.com/coreos/flannel/issues/663
    - name: Apply Drupal 8 Kubernetes services to the cluster.
      shell: >
        curl -sSL "https://github.com/coreos/flannel/blob/master/Documentation/kube-flannel.yml?raw=true" |
        sed "s/amd64/arm/g" |
        kubectl apply -f -
      register: flannel_result
      changed_when: "'created' in flannel_result.stdout"
      run_once: True

    - include_tasks: tasks/nfs.yml
      tags: ['nfs']

    - import_tasks: tasks/led-monitor.yml
      tags: ['leds']

    - import_tasks: tasks/drupal-k8s.yml
      tags: ['drupal']
