---
- hosts: dramble
  become: yes

  vars_files:
    - vars/main.yml
    - config.yml

  pre_tasks:
    - import_tasks: tasks/test-setup.yml
      when: deploy_target != 'pi'

    - name: Ensure dependencies are installed.
      apt: name={{ item }} state=present
      with_items:
        - sudo
        - openssh-server

    - import_tasks: tasks/cgroup-features.yml
    - import_tasks: tasks/disable-swap.yml
      tags: ['always']

  roles:
    # TODO: Re-enable firewall once I can figure out exactly which ports are
    # required to get cni, flannel, etc. all working correctly.
    # - { role: geerlingguy.firewall, tags: ['firewall'] }

    - role: geerlingguy.security
      tags: ['security']

    - role: geerlingguy.nfs
      tags: ['nfs']
      when: deploy_target != 'docker'

    - role: geerlingguy.pip
      tags: ['pip', 'docker']

    - role: docker-arm
      tags: ['docker']

    - role: geerlingguy.kubernetes
      tags: ['kubernetes']

    - role: leds
      tags: ['leds']

  tasks:
    # TODO: See https://github.com/coreos/flannel/issues/663
    - name: Apply Drupal 8 Kubernetes services to the cluster.
      shell: >
        curl -sSL "https://github.com/coreos/flannel/blob/master/Documentation/kube-flannel.yml?raw=true" |
        sed "s/amd64/arm/g" |
        kubectl apply -f -
      register: flannel_result
      changed_when: "'created' in flannel_result.stdout"
      run_once: True
      when: deploy_target == 'pi'

    - include_tasks: tasks/nfs.yml
      tags: ['nfs']
      when: deploy_target != 'docker'

    - import_tasks: tasks/led-monitor.yml
      tags: ['leds']

    - import_tasks: tasks/k8s-services.yml
      tags: ['kubernetes']

    - import_tasks: tasks/k8s-docker-registry.yml
      tags: ['kubernetes', 'docker']

    - import_tasks: tasks/k8s-drupal8.yml
      tags: ['drupal']
