---
- name: Ensure MySQL volume mount dir exists.
  file:
    path: /var/drupal8-mysql
    state: directory

- name: Copy Kubernetes definition files to the cluster.
  template:
    src: "{{ item }}"
    dest: "~/{{ item | basename }}"
  with_fileglob: "files/manifests/drupal8/*.yml"

- name: Apply Drupal 8 Kubernetes services to the cluster.
  command: kubectl apply -f ~/{{ item }}
  with_items:
    - drupal8-metadata.yml
    - drupal8.yml
    - drupal8-mysql.yml
  register: kube_apply_result
  changed_when: "'created' in kube_apply_result.stdout"
  delegate_to: "{{ groups.dramble[0] }}"
  run_once: True
