---
- name: Copy Kubernetes definition files to the cluster.
  template:
    src: "{{ item }}"
    dest: "~/{{ item | basename }}"
  with_fileglob: "k8s-manifests/nfs/*.yml"
  delegate_to: "{{ groups.dramble[0] }}"
  run_once: True

- name: Apply NFS Kubernetes services to the cluster.
  command: kubectl apply -f ~/{{ item }}
  with_items:
    - nfs-rbac.yml
    - nfs-deployment.yml
    - nfs-storageclass.yml
  register: kube_apply_result
  changed_when: "'created' in kube_apply_result.stdout"
  delegate_to: "{{ groups.dramble[0] }}"
  run_once: True
