---
- name: Ensure /var/www directory exists.
  file:
    path: /var/www
    state: directory
    mode: 0755

- name: Ensure drupal_docroot exists.
  file:
    path: "{{ drupal_docroot }}"
    state: directory
    mode: 0755
    owner: www-data
    group: www-data

- name: Ensure staging config directory has correct permissions.
  file:
    path: "{{ drupal_docroot }}/sites/default/config/staging"
    state: directory
    mode: 0755
    owner: www-data
    group: www-data
  when: drupal_install_complete.stat.exists

- name: Check out Drupal to the docroot.
  git:
    repo: "{{ drupal_repo }}"
    version: "{{ drupal_version }}"
    update: "{{ drupal_keep_updated }}"
    force: yes
    dest: "{{ drupal_docroot }}"
  register: project_updated
  notify: restart nginx
  sudo_user: www-data

- name: Apply necessary patches for Drupal core.
  shell: >
    curl https://www.drupal.org/files/issues/{{ item }} | git apply
    chdir={{ drupal_docroot }}
  with_items:
    - rebuilding_service-2497243-188.patch
    - race_conditions_in_the-2429659-114.patch
  when: project_updated.changed

- name: Copy settings.php file into place.
  template:
    src: ../templates/settings.php.j2
    dest: "{{ drupal_docroot }}/sites/default/settings.php"
    owner: www-data
    group: www-data
  notify: restart nginx

- name: Set permissions on settings.php (pre-install).
  file:
    path: "{{ drupal_docroot }}/sites/default/settings.php"
    mode: 0664
  when: not drupal_install_complete.stat.exists

- name: Ensure settings.php has proper permissions.
  file:
    path: "{{ drupal_docroot }}/sites/default/settings.php"
    mode: 0644
  when: drupal_install_complete.stat.exists
