---
- name: Ensure Drupal files folder exists.
  file:
    path: "{{ gluster_mount_dir }}/files"
    state: directory
    owner: www-data
    group: www-data
    mode: 0755

- name: Symlink Drupal files folder into place.
  file:
    src: "{{ gluster_mount_dir }}/files"
    dest: "{{ drupal_docroot }}/sites/default/files"
    state: link
    force: yes
