---
- hosts: database
  sudo: yes

  vars_files:
    - ../vars.yml
    - vars.yml

  pre_tasks:
    - include: mounts.yml

    - name: Ensure the data directory for mysql exists.
      file:
        path: "{{ mysql_datadir }}"
        state: directory
        owner: mysql
        group: mysql
        mode: 0755
      when: "mysql_datadir != '/var/lib/mysql'"

  roles:
    - geerlingguy.firewall
    - geerlingguy.mysql
