---
- name: Ensure SSD mount point exists.
  file:
    path: /ssd
    state: directory
    mode: 0755

- name: Ensure SSD mount exists.
  mount:
    name: /ssd
    src: /dev/sda1
    fstype: ext4
    opts: "rw,noatime,data=ordered"
    state: present
