# PersistentVolume for Drupal 8 MySQL database.
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-db-pv
  namespace: drupal8
  labels:
    app: drupal8
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: {{ nfs_share_dir }}/drupal8-db
    server: {{ kubernetes_master_ip }}
  persistentVolumeReclaimPolicy: Recycle
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-db-pvc
  namespace: drupal8
  labels:
    app: drupal8
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi

# MySQL Deployment.
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql
  namespace: drupal8
  labels:
    app: drupal8
spec:
  selector:
    matchLabels:
      app: drupal8
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: drupal8
        tier: mysql
    spec:
      containers:
      - image: {{ mysql_container_image }}
        name: mysql
        env:
        - name: MYSQL_DATABASE
          value: drupal
        - name: MYSQL_USER
          value: drupal
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: drupal8-mysql-pass
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: drupal8-mysql-root-pass
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-db-pvc

# MySQL Service.
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: drupal8
  labels:
    app: drupal8
spec:
  ports:
  - port: 3306
  selector:
    app: drupal8
    tier: mysql
  clusterIP: None
