---
# PersistentVolume definition for NFS mount for Drupal 8 files.
apiVersion: v1
kind: PersistentVolume
metadata:
  name: drupal8-files-pv
  labels:
    app: drupal8
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: {{ nfs_share_dir }}/drupal8-files
    server: {{ groups.dramble[0] }}
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal8-files-pvc
  labels:
    app: drupal8
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
# Drupal 8 Service definition.
apiVersion: v1
kind: Service
metadata:
  name: drupal8
  labels:
    app: drupal8
spec:
  ports:
    - port: 80
  selector:
    app: drupal8
    tier: frontend
  type: NodePort
---
# Drupal 8 Deployment definition.
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: drupal8
  labels:
    app: drupal8
spec:
  selector:
    matchLabels:
      app: drupal8
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: drupal8
        tier: frontend
    spec:
      containers:
        - image: geerlingguy/drupal:latest
          imagePullPolicy: Always
          name: drupal8
          env:
            - name: DRUPAL_DB_HOST
              value: drupal8-mysql
            - name: DRUPAL_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: drupal8-mysql-pass
                  key: password
          ports:
            - containerPort: 80
              name: drupal8
          volumeMounts:
            - mountPath: /var/www/html/sites/default/files
              name: drupal8-files
      volumes:
        - name: drupal8-files
          persistentVolumeClaim:
            claimName: drupal8-files-pvc
