---
site_name: Dramble
site_url: pidramble.com
drupal_docroot: /var/www/drupal

# Drupal filesystem configuration.
gluster_mount_dir: /mnt/gluster

# Networking configuration.
networking_default_gateway: 10.0.1.1
