---
- hosts: webservers
  sudo: yes
  serial: 1

  vars_files:
    - ../vars.yml
    - vars/main.yml

  tasks:
    - name: Check if Drupal has already been installed.
      stat: path=/var/local/drupal_install_complete
      register: drupal_install_complete

    - include: tasks/deploy.yml

    - include: tasks/files.yml

    - include: tasks/install.yml
      when: not drupal_install_complete.stat.exists

    - include: tasks/update.yml
      when: drupal_install_complete.stat.exists

    - include: tasks/cron.yml

  handlers:
    - include: handlers/main.yml
