---
- hosts: webservers
  sudo: yes
  serial: 1

  vars_files:
    - ../vars.yml
    - vars.yml

  tasks:
    - name: Check if Drupal has already been installed.
      stat: path=/var/local/drupal_install_complete
      register: drupal_install_complete

    - include: deploy.yml
    - include: files.yml

    - include: install.yml
      when: not drupal_install_complete.stat.exists

    - include: update.yml
      when: drupal_install_complete.stat.exists

    - include: cron.yml

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted

    - name: restart php-fpm
      service: name=php-fpm state=restarted
