---
- hosts: balancer
  sudo: yes

  vars_files:
    - ../vars.yml
    - vars.yml

  roles:
    - geerlingguy.firewall
    - geerlingguy.nginx

  tasks:
    - name: Copy vhost configuration into place.
      copy:
        src: balancer.conf
        dest: /etc/nginx/sites-enabled/balancer.conf
        mode: 0644
      notify: restart nginx
