---
firewall_allowed_tcp_ports:
  - 22
  - 80

# Nginx configuration.
nginx_default_release: wheezy-backports # For Nginx 1.6.x instead of 1.2.x.
nginx_worker_processes: "4" # Set to number of CPU cores on Pi.
nginx_worker_connections: "1024"
nginx_access_log: "off"
nginx_keepalive_timeout: "1"
nginx_keepalive_requests: "1000"
nginx_proxy_cache_path: "/var/cache/nginx keys_zone=cache:32m max_size=1g inactive=15m"
nginx_remove_default_vhost: true
nginx_vhosts: []
nginx_upstreams:
  - {
    name: dramble,
    # Options: 'least_conn', 'ip_hash' (if not set, round-robin will be used).
    # strategy: "",
    servers: "{{ groups.webservers }}"
  }
